spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/youbo
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# custom config
ftp:
  server:
    ip: 127.0.0.1
    http-prefix: http://image.youbo.io/
  username: youboadmin
  password: 123456